### ISSUE TITLE
NTR: Request for S05 standardised to a reference pressure level using concurrent CTD profile data

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#1]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>standardised to a reference pressure level using concurrent CTD profile data <p><b>Definition</b><p> The value has been calculated using concurrent CTD profile data such as temperature and salinity, according to a reference pressure level specified in the usage metadata.<p><H2> Optional </H2><p><b>Sources/references</b><p> Taken from Parameter and P01 definitions<p> <b>Mapping to other terminologies </b><p> For the migration to GP_MODEL of: http://vocab.nerc.ac.uk/collection/P01/current/TRTM2WPR/<p>

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/S05/current/S050261
