### ISSUE TITLE
NTR: Request for S05 computation using equations from Legendre and Gosseline (1996)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#12]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>computation using equations from Legendre and Gosseline (1996) <p><b>Definition</b><p> The parameter has been calculated using the equations published in Legendre, L., and Gosseline, M. (1996). Estimation of N and C uptake rates by phytoplankton using 15N and 13C: revisiting the usual computation formulae. J. Plankt. Res. 19, 263-271.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://jira.ceh.ac.uk/browse/BODCNVS-1325<p>

**Comment by roswri** [comment]
Code created:
S050242 - computation using equations from Legendre and Gosseline (1996)
