### ISSUE TITLE
NTR: Request for S05 computation using the haversine formula

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#15]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>computation using the haversine formula <p><b>Definition</b><p> The parameter has been calculated using the haversine formula to determine the angular distance between two points on the surface of a sphere.<p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
This term has now been created and will be live on the NVS from 0730 UTC tomorrow morning.
S050247	computation using the haversine formula

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S05/current/S050247/
