### ISSUE TITLE
NTR: Request for S05 computation from areal extent multiplied by the coverage ratio

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>computation from areal extent multiplied by the coverage ratio <p><b>Definition</b><p> The result was obtained by multiplying the areal extent of an object by its coverage ratio.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
The term is live on the NVS: http://vocab.nerc.ac.uk/collection/S05/current/S050250/
