### ISSUE TITLE
NTR: derivation from a global grid specified elsewhere

### ISSUE THREAD

**Issue by JordanAthertonNOC** [nvs-vocabs/S05#18]
New S05 term required to facilitate the creation of one new sea-floor depth P01 term for Ifremer. 

`derivation from a global grid specified elsewhere`

Similar to [S050145](http://vocab.nerc.ac.uk/collection/S05/current/S050145/)

**Comment by gwemon** [comment]
@JordanAthertonNOC I think it would be good to have the link to the P01 issue ticket because it gives the context in which this processing method is needed.

**Comment by JordanAthertonNOC** [comment]
Hi @gwemon not to worry - on the list of things to do

**Comment by JordanAthertonNOC** [comment]
Removing `specified elsewhere` from the preflabel, as this is in reference to "the global grid will be described as a global attribute of the netCDF file". This part is not required in the S05 preflabel.

**Comment by JordanAthertonNOC** [comment]
This term is no longer required as the P01 term this S05 was required for has been modelled differently.
