### ISSUE TITLE
NTR: Request for S05 classification to a term from Nanson et al. (2023)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>classification to a term from Nanson et al. (2023) <p><b>Definition</b><p> The observation has been classified using a term defined in the Geomorphology Classification Framework and Glossary - Version 1.0 (Nanson et al. (2023), published at https://doi.org/10.5281/zenodo.7804019.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://doi.org/10.5281/zenodo.7804019<p>

**Comment by danibodc** [comment]
Associated with https://github.com/nvs-vocabs/P01/issues/215

**Comment by danibodc** [comment]
This term has been loaded and will be live on the NVS from tomorrow morning:

S050252	classification to a term from Nanson et al. (2023)

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S05/current/S050252/
