### ISSUE TITLE
NTR: Request for S05 near real-time data processing

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#2]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>near real-time data processing <p><b>Definition</b><p> A data processing method indicating that the data have been transformed using only fully automated data processing techniques operating within the constraints of a near-real time data system with respect to transmission volume and processing power.<p><H2> Optional </H2><p><b>Sources/references</b><p> This data processing component is needed to support the creation of a new set of P01 parameter codes for NRT-processed LISST-200X particle size and concentration data.<p> <b>ORCID</b><p> https://orcid.org/0000-0001-6559-4178<p>

**Comment by danibodc** [comment]
The new S05 term has now been created:

S050225 - processing in near real-time
http://vocab.nerc.ac.uk/collection/S05/current/S050225/
