### ISSUE TITLE
NTR: computation from Equivalent Spherical Diameter (ESD)

### ISSUE THREAD

**Issue by danibodc** [nvs-vocabs/S05#20]
Pref label: computation from Equivalent Spherical Diameter (ESD)

Description: The parameter was computed assuming the entity was spherical in shape, using its Equivalent Spherical Diameter (ESD).

**Comment by danibodc** [comment]
Related to https://github.com/nvs-vocabs/P01/issues/61

**Comment by gwemon** [comment]
Or I think we could just say: "The parameter was calculated assuming the particle(s) observed is/are spherical in shape."

**Comment by danibodc** [comment]
The term has been loaded and will be live on the NVS from tomorrow morning:

S050253	computation from Equivalent Spherical Diameter (ESD)	

Description:
The parameter was calculated assuming the particle(s) observed is/are spherical in shape.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S05/current/S050253/
