### ISSUE TITLE
Suggested revision of S050057

### ISSUE THREAD

**Issue by sformel-usgs** [nvs-vocabs/S05#25]
The preferred label on [TEMPCU01](https://vocab.nerc.ac.uk/collection/P01/current/TEMPCU01/) threw me off: `Temperature of the water body by CTD and NO verification against independent measurements`. 

Since I couldn't see the definition in the facet search, I thought NO == Nitric Oxide. This interpretation is consistent with capitalization representing acronyms, not emphasis, across the terms. 

I suggest revising the term [S05](https://vocab.nerc.ac.uk/collection/S05/current/):[S050057](https://vocab.nerc.ac.uk/collection/S05/current/S050057/) to use 'without' instead of using 'NO'

**Comment by danibodc** [comment]
Thank you @sformel-usgs, we have a number of S05 terms where the 'NO' is capitalised. These were created quite a few years ago now, with the aim of distinguishing these from terms where verification/calibration/corrections had been applied. We agree this is misleading so have replaced the capitalisation of 'NO' with lowercase 'no'.

The changes should be live on the NVS from tomorrow morning. Many thanks!
