### ISSUE TITLE
NTR: Request for S05 classification using the Everyone's Gliding Observatories (EGO) format reference manual (https://doi.org/10.13155/34980) (BODCNVS-1083)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>classification using the Everyone's Gliding Observatories (EGO) format reference manual (https://doi.org/10.13155/34980) <p><b>Definition</b><p> The classification used is published as a reference table within the Everyone's Gliding Observatories (EGO) gliders NetCDF format reference manual, with the latest version published at https://doi.org/10.13155/34980<p><H2> Optional </H2><p><b>Mapping to other terminologies </b><p> Not currently available as a controlled vocabulary<p><p>https://github.com/nvs-vocabs/P01/issues/83</p>

**Comment by gwemon** [comment]
I would say: "classification using a term defined in the Everyone's Gliding Observatories (EGO) format reference list  (https://doi.org/10.13155/34980)"

**Comment by danibodc** [comment]
This term has now been created:

**Code:** S050238	
**Preferred label:** classification to a term from the Everyone's Gliding Observatories (EGO) format reference list (https://doi.org/10.13155/34980)	
**Definition:** The classification used is published as a reference table within the Everyone's Gliding Observatories (EGO) gliders NetCDF format reference manual, with the latest version published at https://doi.org/10.13155/34980.

It will be live on the NVS from 0730 UTC tomorrow morning.

**Comment by danibodc** [comment]
This code is now live:
https://vocab.nerc.ac.uk/collection/S05/current/S050238/
